name = "cotamweb-v1"
main = "src/index.js"
compatibility_date = "2024-09-02"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "cotamweb_db"
database_id = "28a650a0-5e39-4dfe-8261-8f36cdd70b53"